### ISSUE TITLE
ERROR TypeError: Object http://ja.wikipedia.org/wiki/Category:料理 has no method 'then'

### ISSUE THREAD

**Issue by koooge** [shokai/hubot-gohan#3]
hubot> hubot gohan
[Sat May 30 2015 16:32:55 GMT+0000 (UTC)] ERROR TypeError: Object http://ja.wikipedia.org/wiki/Category:料理 has no meth
od 'then'
  at Gohan.module.exports.Gohan.getGohan (/home/hubot/hubot/node_modules/hubot-gohan/lib/gohan.coffee:66:24, <js>:98:79)

  at TextListener.callback (/home/hubot/hubot/node_modules/hubot-gohan/scripts/hubot-gohan.coffee:22:5, <js>:18:20)
  at TextListener.Listener.call (/home/hubot/hubot/node_modules/hubot/src/listener.coffee:27:7, <js>:23:14)
  at Robot.receive (/home/hubot/hubot/node_modules/hubot/src/robot.coffee:197:9, <js>:143:33)
  at Shell.Adapter.receive (/home/hubot/hubot/node_modules/hubot/src/adapter.coffee:66:5, <js>:47:25)
  at [object Object].listener (/home/hubot/hubot/node_modules/hubot/src/adapters/shell.coffee:48:7, <js>:92:22)
  at [object Object].Cli.parse (/home/hubot/hubot/node_modules/hubot/node_modules/cline/index.js:320:35)
  at [object Object].<anonymous> (/home/hubot/hubot/node_modules/hubot/node_modules/cline/index.js:182:18)
  at [object Object].defaultFn (/home/hubot/hubot/node_modules/hubot/node_modules/cline/index.js:53:13)
  at [object Object].fn (/home/hubot/hubot/node_modules/hubot/node_modules/cline/index.js:217:23)
  at Interface.<anonymous> (/home/hubot/hubot/node_modules/hubot/node_modules/cline/index.js:148:18)
  at Interface.emit (events.js:95:17)
  at Interface._onLine (readline.js:203:10)
  at Interface._line (readline.js:532:8)
  at Interface._ttyWrite (readline.js:761:14)
  at ReadStream.onkeypress (readline.js:100:10)
  at ReadStream.emit (events.js:98:17)
  at emitKey (readline.js:1096:12)
  at ReadStream.onData (readline.js:841:14)
  at ReadStream.emit (events.js:95:17)
  at ReadStream.<anonymous> (_stream_readable.js:765:14)
  at ReadStream.emit (events.js:92:17)
  at emitReadable_ (_stream_readable.js:427:10)
  at emitReadable (_stream_readable.js:423:5)
  at readableAddChunk (_stream_readable.js:166:9)
  at ReadStream.Readable.push (_stream_readable.js:128:10)
  at TTY.onread (net.js:529:21)

**Comment by koooge** [comment]
coffee-scriptが古いとだめなのですね、
http://shokai.org/blog/archives/9387

% npm install coffee-script -save

**Comment by shokai** [comment]
これはREADMEに書いておかないといけないですね
